### ISSUE TITLE
Error compiling 

### ISSUE THREAD

**Issue by jonyluke** [crumblingstatue/gmktool#5]
error: aborting due to 20 previous errors

For more information about this error, try `rustc --explain E0446`.
error: Could not compile `rgmk`.

**Comment by crumblingstatue** [comment]
I'll look into it, but note that this project isn't being actively developed, so it might not even work for what you want to do.

**Comment by jonyluke** [comment]
I am trying to make the translation of Undertale (nintendo switch version) into Spanish

**Comment by crumblingstatue** [comment]
I only ever tested this on the PC version of undertale, so I doubt it works with the switch version.

**Comment by crumblingstatue** [comment]
Welp, it looks like I started a rewrite like 2 years ago, but I never finished it, leaving the code broken.

Since I currently don't have an interest in this project, I'll declare it unmaintained.

I advise you to seek out a different tool for this job.

**Comment by crumblingstatue** [comment]
@jonyluke I found https://github.com/fjay69/UndertaleTools , and it seems to be maintained, and it might even work for the switch version.

**Comment by jonyluke** [comment]
I found a solution with https://github.com/krzys-h/UndertaleModTool
